name: 'Taro React Native Release'
description: 'Taro React Native Release'
author: 'Tony Chen'
inputs:
  token:
    required: true
    description: 'github token'
  publicpath:
    required: false
    description: 'asset public path'
    default: 'https://cdn.jsdelivr.net/gh'
  tag:
    required: false
    description: 'tag name'
  iosbundlepath:
    required: false
    description: 'ios bundle path'
    default: 'ios/main.js'
  iosqrpath:
    required: false
    description: 'ios qr path'
    default: 'release/qrcode/ios.png'
  androidbundlepath:
    required: false
    description: 'android bundle path'
    default: 'android/main.js'
  androidqrpath:
    required: false
    description: 'android qr path'
    default: 'release/qrcode/android.png'
  appname:
    required: false
    description: 'app name'
  logo:
    required: false
    description: 'app logo'
runs:
  using: 'node12'
  main: 'dist/index.js'
